-- MySQL Script generated by MySQL Workbench
-- Do 12 Aug 2021 11:17:52 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema verdant
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `verdant` ;

-- -----------------------------------------------------
-- Schema verdant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `verdant` ;
USE `verdant` ;

-- -----------------------------------------------------
-- Table `verdant`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `verdant`.`user` ;

CREATE TABLE IF NOT EXISTS `verdant`.`user` (
  `uuid` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdant`.`interactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `verdant`.`interactions` ;

CREATE TABLE IF NOT EXISTS `verdant`.`interactions` (
  `id` INT NOT NULL,
  `uuid` VARCHAR(256) NULL,
  `holding_name` VARCHAR(512) NULL,
  `ticker_symbol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdant`.`metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `verdant`.`metadata` ;

CREATE TABLE IF NOT EXISTS `verdant`.`metadata` (
  `id` INT NOT NULL,
  `ticker_symbol` VARCHAR(45) NULL,
  `average_rating` VARCHAR(45) NULL,
  `marcet_cap` VARCHAR(45) NULL,
  `average_volume` VARCHAR(45) NULL,
  `country_code` VARCHAR(45) NULL,
  `industry` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `employees` VARCHAR(45) NULL,
  `overall_risk` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
